### ISSUE TITLE
DcGeneral, error with version 2.0.0-beta39

### ISSUE THREAD

**Issue by stefanheimes** [menatwork/syncCto#277]
The new version of the DCG (2.0.0-beta39) throws an error:
```php
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php(65): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(284): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC/General.php(344): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#8 system/modules/core/classes/Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->edit()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('synccto_clients')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}```

**Comment by stefanheimes** [comment]
If you use only the DCG for SyncCto without MetaModels, the best workaround is to go back to the version 2.0.0-beta38 of the DCG. 

The best way to do this, is to add the following row to you composer.json in you composer folder:

```contao-community-alliance/dc-general": "=2.0.0-beta38",```

The whole file should look like this: 
```
{
    "name": "local/website",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0+",
    "version": "3.2.0",
    "type": "project",
    "require": {
        "contao-community-alliance/composer-client": ">=0.16.2.0,<0.17-dev",
	"contao-community-alliance/dc-general": "=2.0.0-beta38",		
        "dma/dma_elementgenerator": "dev-master",
        "guzzlehttp/guzzle": "~6.2",
        "menatwork/synccto": ">=3.2.0,<3.3-dev",
        "terminal42/contao-ce-access": ">=2.0.3.0,<2.1-dev"
    },
    "config": {
        "preferred-install": "source",
        "cache-dir": "cache",
        "component-dir": "../assets/components",
        "discard-changes": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "contao": {
            "migrated": "done"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://legacy-packages-via.contao-community-alliance.org/"
        },
        {
            "type": "artifact",
            "url": "packages"
        }
    ]
}
```

**Comment by mammut47** [comment]
The same applies to my installation. Same Error. Reverting to 2.0.0.-beta38 works. But this is only a workaround. Not a solution

**Comment by stefanheimes** [comment]
Jip just a quickfix. I have to make some updates in SyncCto for this. I hope i can do it this week.

**Comment by zonky2** [comment]
test  	dev-hotfix/3.2.4 (0123c19d):
* sync works fine
* backup doesn´t work same error `...Unparsable encoded id value: ''...`

**Comment by stefanheimes** [comment]
Fixe all with new version 3.2.4 and commit ab4e12b353ca44bd74a07d90b46218d1d7403ddf
